# Default colors
[colors.primary]
background = '#010414'
foreground = '#EBEBEB'

# Cursor colors
[colors.cursor]
text = '#2e3436'
cursor = '#FFC620'

# Normal colors
[colors.normal]
black   = '#a7a2a9'
red     = '#bd0013'
green   = '#3cb371'
yellow  = '#bf7f00'
blue    = '#3d44ba'
magenta = '#bf0fbf'
cyan    = '#89d1ec'
white   = '#6e7476'
# Bright colors
[colors.bright]
black   = '#FEFEF8'
red     = '#ff5454'
green   = '#00ffaf'
yellow  = '#ffff54'
blue    = '#1f6cff'
magenta = '#e75699'
cyan    = '#1cfafe'
white   = '#aaaaaa'
[font.normal]
family="FiraCode Nerd Font"
#family="Cousine Nerd Font"
style = "Regular"

[font]
size = 7

[font.offset]
x = 0
y = -1

[keyboard]
bindings = [ { key = "Return", mods = "Shift", chars = "\n" } ]
