#!/bin/bash

dotfiles="$(dirname "$(dirname "$(readlink -f "$0")")")"

dot_cp() {
    cp "$HOME/$2" "$1"
}

find $dotfiles -mindepth 1 \( -name '[+.]*' -prune -o -not -type d -type f -print \) | while read f; do
    dot_cp "$f" ".${f#$dotfiles/}"
done
