#! /bin/zsh

export EMAIL="aurelien.lajoie@utix.fr"
export NAME="Aurélien LAJOIE"
export FULLNAME="$NAME"

export MANWIDTH=80
export EDITOR=vim
export VISUAL=vim
export CCACHE_DIR="$HOME/.cache/ccache"
export CCACHE_NOCOMPRESS=NoThanks
export CCACHE_HARDLINK=YesPlease


export LC_MESSAGES=C
unset  LC_ALL
unset  VERBOSE

if [ $UID -eq 0 ]; then
    PATH=~root/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
    if test ! -n TERMINFO; then
        export TERMINFO=/home/aurel/.local/kitty.app/lib/kitty/terminfo
    fi
else
    PATH="${HOME}/local/bin:/usr/lib/ccache:${HOME}/bin:${PATH}"
    LD_LIBRARY_PATH="${HOME}/local/lib"
fi

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUAL_ENV_DISABLE_PROMPT=1
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/home/aurel/.local/bin/virtualenv
source /home/aurel/.local/bin/virtualenvwrapper.sh
export M3_HOME=/opt/apache-maven-3.3.9
export M3=$M3_HOME/bin
export PATH=$M3:$PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
