#! /bin/zsh

export EMAIL="aurelien.lajoie@utix.fr"
export NAME="Aurélien LAJOIE"
export FULLNAME="$NAME"

export MANWIDTH=80
export EDITOR=vim
export VISUAL=vim
export CCACHE_DIR="$HOME/.cache/ccache"
export CCACHE_NOCOMPRESS=NoThanks
export CCACHE_HARDLINK=YesPlease


export LC_MESSAGES=C
unset  LC_ALL
unset  VERBOSE

if [ $UID -eq 0 ]; then
    PATH=~root/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
    if test ! -n TERMINFO; then
        export TERMINFO=$HOME/.local/kitty.app/lib/kitty/terminfo
    fi
else
    PATH="/home/linuxbrew/.linuxbrew/bin:${HOME}/.local/bin:${HOME}/local/bin:/usr/lib/ccache:${HOME}/bin:${PATH}"
    LD_LIBRARY_PATH="${HOME}/local/lib"
fi

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUAL_ENV_DISABLE_PROMPT=1
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=$HOME/.local/bin/virtualenv
#source $HOME/.local/bin/virtualenvwrapper.sh
export M3_HOME=/opt/apache-maven-3.3.9
export M3=$M3_HOME/bin
export PATH=$M3:$PATH
if [ -n "$DESKTOP_SESSION" ]; then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi


export GOPATH=$HOME/dev/go
export PATH=$PATH:/usr/local/go/bin
# Mise CLI
eval "$(mise activate zsh)"
