# === Font ===
font_family FiraCode Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.5

# === Emoji fallback ===
symbol_map U+1F300-U+1F6FF Noto Color Emoji
symbol_map U+1F900-U+1F9FF Noto Color Emoji
symbol_map U+2700-U+26FF Noto Color Emoji
# === Colors ===

foreground #EBEBEB
background #010414
cursor     #FFC620
cursor_text_color #2e3436

color0  #2e3436
color1  #bd0013
color2  #3cb371
color3  #bf7f00
color4  #5c80ff
color5  #bf0fbf
color6  #89d1ec
color7  #b2b2b2

color8  #cdcdcd
color9  #ff5454
color10 #00ffaf
color11 #ffff54
color12 #1f6cff
color13 #e75699
color14 #1cfafe
color15 #FEFEF8

# === Other useful settings ===

confirm_os_window_close 0
enable_audio_bell no
disable_ligatures always
